### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
https://dev-blog-nrrd.app.cloud.gov/

### CODE REVIEW

**Review by mcharg — APPROVED** [review]
Looks good.

**Review by daniel-coleman-1 — APPROVED** [review]

**Comment by cthomasONRR** [comment]
@Maroyafaied Does the date need to be updated? Right now it says January 7.

**Comment by Maroyafaied** [comment]
@cthomasONRR date is updated.

**Review by cthomasONRR — APPROVED** [review]
Thanks for updating the date. Looks good!

**Pull request merged**
