### PR TITLE
Blog Links

### PR DESCRIPTION
**Pull request by daniel-coleman-1**
Correcting links in blog.

Fixes #<[103](https://github.com/ONRR/blog-nrrd/issues/103)>
https://dev-blog-nrrd.app.cloud.gov/intern-onrr-dot-gov/

Fixes #<[104](https://github.com/ONRR/blog-nrrd/issues/104)> 
https://dev-blog-nrrd.app.cloud.gov/shaping/

Fixes #<[105](https://github.com/ONRR/blog-nrrd/issues/105)>
https://dev-blog-nrrd.app.cloud.gov/product-champion/

 Fixes #<[106](https://github.com/ONRR/blog-nrrd/issues/106)>
https://dev-blog-nrrd.app.cloud.gov/beyond-open-data/

Fixes #<[108](https://github.com/ONRR/blog-nrrd/issues/108)>
https://dev-blog-nrrd.app.cloud.gov/usability-testing-training/

[Preview](https://dev-blog-nrrd.app.cloud.gov/)

### CODE REVIEW

**Comment by mcharg** [comment]
@daniel-coleman-1 I'm getting a 404 on the preview link.

**Comment by mcharg** [comment]
I accidentally merged this into dev trying to get the preview link to work.  @jlouis-onrr @mojobnichols How do I unmerge?  The changes don't appear to be reflected in dev anyway.

**Comment by mcharg** [comment]
@daniel-coleman-1 This branch appears to be wonky.  Can you create a new branch with the changes?  We're supposed to see a revert button, but we're not and the changes aren't showing up in dev anyway.

**Comment by mcharg** [comment]
These are now showing up in dev.  It appears to have been a cache issue.  @daniel-coleman-1 You'll have to create a new PR for any changes.  I'll note them on the original issues.

**Comment by mcharg** [comment]
@daniel-coleman-1 #106 and #108 need edits.

**Comment by daniel-coleman-1** [comment]
@mcharg can I make those edits in Cat's blog post PR, or should I make a new one after we merge the blog post PR?

**Comment by mcharg** [comment]
@daniel-coleman-1 I think that's a good idea, so we don't end up with clashing again.

**Pull request merged**
