### PR TITLE
Accessibility beyond auto checks

### LINKED ISSUE #133: Write a blog post about making the org chart accessible beyond the auto checks
Both Christina and Sid will be collaborating with me.

### PR DESCRIPTION
**Pull request by mcharg**
Fixes #133, #127 
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/beyond-auto)

* Added new post about [getting beyond auto checks](https://dev-blog-nrrd.app.cloud.gov/beyond-auto).
* Updated author file to get rid of "is a" and capitalized all author titles.
* Added product disclaimer to the bottom of the post template.
* Added onrr.gov to the footer.

### CODE REVIEW

**Comment by mcharg** [comment]
Sent to Sid and Christina to review. Waiting on photo from Christina, but otherwise ready to review.

**Review by cthomasONRR — APPROVED** [review]
I read through, and can't find any issues. Approving :)

**Comment by mcharg** [comment]
Christina's pic is now in.

**Review by Maroyafaied — APPROVED** [review]
Looks great.

**Review by lpgoldstein — APPROVED** [review]

**Pull request merged**
