### PR TITLE
Adds troubleshooting blog post

### LINKED ISSUE #117: Blog post about troubleshooting wizard
When we finish it, we should write a blog post.

### PR DESCRIPTION
**Pull request by mcharg**
Fixes #117, #138, #93
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/troubleshooting)

* Adds troubleshooting blog post
* Adds default author image
* Adds message to email us for feedback or ideas to the footer

### CODE REVIEW

**Review by cthomasONRR — APPROVED** [review]
Blog looks great! Approving.

**Review by lpgoldstein — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]
Looks great!

**Comment by mcharg** [comment]
@codyeckstein This is just waiting for your approval.

**Comment by codyeckstein** [comment]
Looks good.

**Pull request merged**
