### PR TITLE
dev-->main

### PR DESCRIPTION
**Pull request by lpgoldstein**
Adds Shannon's transition blog post
Fixes eiti link 
[Preview](https://dev-blog-nrrd.app.cloud.gov/)

### CODE REVIEW

**Review by cthomasONRR — APPROVED** [review]
Blog looks good. Approved :)

**Comment by daniel-coleman-1** [comment]
The new EITI link didn't populate to dev for me

**Comment by cthomasONRR** [comment]
I'm seeing the EITI links updated here: https://dev-blog-nrrd.app.cloud.gov/making-tough-content-choices/

**Review by daniel-coleman-1 — APPROVED** [review]
Cleared cache 20 times and it's good to go!

**Pull request merged**
