### PR TITLE
Create index.md

### LINKED ISSUE #81: blog post about cross training experience

### PR DESCRIPTION
**Pull request by meshanw**
Cross training blog

Fixes #81
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/Cross-training/)

### CODE REVIEW

**Review by mcharg — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@meshanw great job again, here are a few suggested edits. 

Should there be a question mark here? 
image

We should abbreviate WDO when it's first mentioned so readers know what "WDO" is referring to. 
image

IDM is mentioned earlier but not explained but it's explained later here, maybe we should move the explanation up.

image

image

**Comment by meshanw** [comment]
Thanks @Maroyafaied. I included the edits you suggested.

**Comment by Maroyafaied** [comment]
@codyeckstein @cvojslavek This is Meshan's blog post about her experience cross training. Click the preview link above if you'd like to read it.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 this is waiting your review.

**Review by daniel-coleman-1 — APPROVED** [review]

**Pull request merged**
