### PR TITLE
Blog Links

### LINKED ISSUE #155: Broken link to USEITI withdrawal letter
The withdrawal letter is no longer on the EITI site. We need to see if we can find this elsewhere. It's in Judy's post. https://blog-nrrd.doi.gov/product-champion/

### PR DESCRIPTION
**Pull request by daniel-coleman-1**
Fixes #155 #156 
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/product-champion/) for 155

[Preview](https://dev-blog-nrrd.app.cloud.gov/making-tough-content-choices/) for 156

### CODE REVIEW

**Comment by mcharg** [comment]
@daniel-coleman-1 I merged by outstanding PR into dev and pulled dev into this branch, so it should work now. After it finishes building, please update your preview link to include links to the specific posts that had links updated and add someone to review the PR.

**Comment by daniel-coleman-1** [comment]
@mcharg I'm struggling to find the format for preview links that works and not seeing it in the wiki anywhere, what's the correct format for the preview link?

**Comment by mcharg** [comment]
This is the preview for the blog homepage and then you can navigate to the specific posts to get the link for the post.
https://dev-blog-nrrd.app.cloud.gov/

**Review by mcharg — APPROVED** [review]
Looks good.

**Pull request merged**
