### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<ISSUE NUMBER>
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/)

* Added new post about [getting beyond auto checks](https://dev-blog-nrrd.app.cloud.gov/beyond-auto).
* Updated author file to get rid of "is a" and capitalized all author titles.
* Added product disclaimer to the bottom of the post template.
* Added onrr.gov to the footer.

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@mcharg Thanks, please put tomorrow's date.

**Comment by mcharg** [comment]
@Maroyafaied I noticed that Christa's post is missing here and in my branch.

**Comment by mcharg** [comment]
Do we need to merge Master into Dev?

**Comment by Maroyafaied** [comment]
@Maroyafaied I see Christa's post 
image

**Comment by mcharg** [comment]
@Maroyafaied So weird.

**Comment by mcharg** [comment]
This is what I see.
image

**Comment by mcharg** [comment]
@cthomasONRR @lpgoldstein Can you both look and see if you see Christa's post in dev?

**Comment by mcharg** [comment]
It's not a caching thing because I'm also not seeing it in Firefox. 
image

**Comment by cthomasONRR** [comment]
@Maroyafaied @mcharg I cleared browsing data and did ctrl+F5, and still not seeing it

**Comment by lpgoldstein** [comment]
@Maroyafaied @mcharg I'm not seeing it either

**Comment by mcharg** [comment]
I can see it now!
image

**Comment by cthomasONRR** [comment]
I can see it now too :)

**Review by mcharg — APPROVED** [review]

**Pull request merged**
