### PR TITLE
Kaitlyn blog - DON'T MERGE

### PR DESCRIPTION
**Pull request by lpgoldstein**
[Preview](https://dev-blog-nrrd.app.cloud.gov/)

I'm adding the preview link for this branch https://dev-blog-nrrd.app.cloud.gov/kaitlyn/

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@Maroyafaied This is the blog post where I'm having trouble getting the image to show and adding an author.

**Comment by Maroyafaied** [comment]
@lpgoldstein I was able to add Kaitlyn as an author and get the image to show. I added @cthomasONRR and @kmhtran to review.  I didn't do a very thorough review but notices minor grammar issues in this paragraph (pic below). Also, The preview links still work for the blog so you can view this one with this link https://dev-blog-nrrd.app.cloud.gov/kaitlyn/

**Comment by cthomasONRR** [comment]
@lpgoldstein 
Here are some grammar edits:

Add a comma here:
image

Remove this additional "about":
image

Break up this run-on sentence: 
image

Words missing, and could break up this run-on sentence:
image

Another really long run-on sentence:
image



Did you test in Hemmingway? There are a ton of compound/run-on sentences that were a bit difficult to read.

**Comment by lpgoldstein** [comment]
@Maroyafaied and @cthomasONRR I didn't run through Hemingway because I was going for authentic voice from Kaitlyn and she wrote/edited her own responses. I definitely should have caught the grammar edits though and worked more on the editing process with her and how we usually write. I'll run it through now and make corrections. Thanks for taking the time to review.

**Pull request merged**
