### PR TITLE
Contacts Blog Post

### PR DESCRIPTION
**Pull request by daniel-coleman-1**
[Preview](https://dev-blog-nrrd.app.cloud.gov/contacts/)

### CODE REVIEW

**Review by CM805 — APPROVED** [review]

**Comment by mcharg** [comment]
I'll approve once the alt text is updated.

**Review by mcharg — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 There's a coma and a colon in this sentence (pic below). Also do these lists need a period or a comma after every step? 

image
image

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 please see my comment from last week.

**Comment by mcharg** [comment]
@daniel-coleman-1 Are you going to address Maroya's comments or would you like @cthomasONRR to make the fixes?

**Comment by daniel-coleman-1** [comment]
@mcharg  I put in @Maroyafaied's edits from last sprint, apologies again for the delay.  I think we can close this now.

**Comment by mcharg** [comment]
@daniel-coleman-1 I think Maroya wanted to wait until the new site goes live to publish, so we'll let her merge it then and leave it open.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 the preview link is not working for me , can you work with Mojo or Jerome to fix it so I can review. Thanks

**Comment by mcharg** [comment]
@Maroyafaied It's probably because we have two blog posts out there now and we don't have it set up for multiple preview links.

**Comment by Maroyafaied** [comment]
@mcharg Ok, I'll merge the other one and try.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 the link doesn't work for me still after merging the other blog post.

**Comment by mcharg** [comment]
@Maroyafaied @daniel-coleman-1 I fixed it by merging in the changes from the homepage blog post.

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
