### PR TITLE
Adds transition post

### LINKED ISSUE #150: Write final blog post (for now)

### PR DESCRIPTION
**Pull request by mcharg**
Fixes #150
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/passing-baton/)

### CODE REVIEW

**Comment by mcharg** [comment]
After the agile post goes live, we'll need to pull dev into this branch and the preview link will work.

**Comment by mcharg** [comment]
@lpgoldstein @Maroyafaied This is ready to review. We should hold of on merging to dev until the agile post goes out.

**Review by lpgoldstein — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@mcharg please fix what's underlined in red, otherwise looks good. Thanks
image

**Comment by mcharg** [comment]
@Maroyafaied Link is fixed.

**Review by Maroyafaied — APPROVED** [review]

**Comment by mcharg** [comment]
@lpgoldstein @cthomasONRR I added to the agile paragraph. Can you please review?

**Comment by cthomasONRR** [comment]
@mcharg Looks good, hopefully this will help clarify some of the listserv discourse!

**Pull request merged**
