### PR TITLE
homepage-graphic-redesign

### PR DESCRIPTION
**Pull request by arcasarana**
Still have to add the images.  But this is what I have so far @mcharg @Maroyafaied @CM805

### CODE REVIEW

**Comment by mcharg** [comment]
[Preview](https://dev-blog-nrrd.app.cloud.gov/)

**Comment by CM805** [comment]
Can't get the preview link to load

**Comment by mcharg** [comment]
@CM805 The build keeps failing.  We need help from @mojobnichols or @jlouis-onrr to fix it.

**Comment by jlouis-onrr** [comment]
@mcharg, looks like it is not building due to the colon within the pages frontmatter title, see below:
```
incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 2, column 32:
    title: A user-centered approach: Simplicity and complexity in a ... 
```
    
if you escape the colon it should build, something like:
`title: A user-centered approach\: Simplicity and complexity in a homepage graphic`

**Comment by mcharg** [comment]
@arcasarana @cthomasONRR @CM805 The preview link works now!

**Comment by mcharg** [comment]
@arcasarana What do the numbers mean after the user types?
image

**Comment by CM805** [comment]
Took a look at it and it looks good.  Just wondering if you all want to incorporate the few grammatical changes I made this morning on the draft in Teams.

**Comment by mcharg** [comment]
@CM805 Yes, we should make those changes.  @cthomasONRR Do you want to take a look at Christa's comments in the Teams version and incorporate them into the Markdown file in Atom?

Teams version:
https://teams.microsoft.com/l/file/7ecdf62e-21c4-4e0e-9288-71b4cb1d1594?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FHomepage%20graphic%20blog%20post%20(draft%2003).docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&messageId=1623932538084&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by cthomasONRR** [comment]
@mcharg and @CM805 Sure! I will look at the Teams version and incorporate them into Atom.

**Review by cthomasONRR — APPROVED** [review]
I reviewed the blog post, and updated minor grammar and formatting issues.

**Comment by CM805** [comment]
Is there a way to make the images more clear?

Also, found a place where a comma should be added:

The interviews were conducted by Sarah, Brandi, and Shannon with internal staff who volunteered as notetakers."  should be :
"The interviews were conducted by Sarah, Brandi, and Shannon, with internal staff who volunteered as notetakers."

**Comment by cthomasONRR** [comment]
@CM805 - I updated the blog to include your extra comma. I'm unsure about how to make the images more clear. Maybe @mcharg can help us on that?

**Review by CM805 — APPROVED** [review]
Thanks for addressing my concerns @cthomasONRR

**Comment by mcharg** [comment]
@cthomasONRR Thanks for being on top of the edits!

@CM805 I messaged @branic18 to see if maybe she can save off the images in a different format that isn't fuzzy.

**Comment by mcharg** [comment]
@branic18 responded and said she'll see what she can do to make the images not blurry.

**Comment by mcharg** [comment]
@cthomasONRR @CM805 I made the images less blurry.  Let me know if you think I need to replace any of the other images.

**Review by mcharg — APPROVED** [review]

**Comment by mcharg** [comment]
@arcasarana @branic18 I just realized we didn't have a link to the design we landed on after testing, so I added a link to that in the research outcomes section.

**Comment by cthomasONRR** [comment]
@mcharg I just re-reviewed, and the images look great!

**Review by arcasarana — COMMENTED** [review]
I replaced brandi-1b.png because I couldn't find the original lightning icon.  The one I have in this new version is attributed in the copy of the blog already.

**Comment by mcharg** [comment]
@Maroyafaied This is ready to merge once you review.

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
