### PR TITLE
Added QA Blog

### LINKED ISSUE #31: Publish QA blog post
publish blog post

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #31 
[:sunglasses: PREVIEW](https://dev-blog-nrrd.app.cloud.gov/QA/)
- Adds QA blog post

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@lpgoldstein @jennmalcolm I found the following issues highlighted, also there are no authors listed. 

image

image

image

image

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
This looks good to me.  @jlouis-onrr @jennmalcolm @lpgoldstein  can you review before I merge.

**Comment by mcharg** [comment]
@Maroyafaied I read through the whole thing and didn't notice any typos or anything.

**Review by jennmalcolm — APPROVED** [review]

**Comment by lpgoldstein** [comment]
@jennmalcolm @Maroyafaied @mcharg Thanks for working on this. I don't see any typos either.

**Pull request merged**
