### PR TITLE
Add metrics blog

### LINKED ISSUE #171: PR for metrics blog

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #171 
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/)

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@lpgoldstein Review right now... Are the headers meant to be links? They are just linking to their specific section of this blog: 
image

**Comment by cthomasONRR** [comment]
@lpgoldstein 

This NRRD site link isn't working for me:
image

**Comment by lpgoldstein** [comment]
@cthomasONRR I removed the www from the nrrd link and rebuilt. I'm not sure why those headers are showing up as links. I'm not doing anything special to them to make them links. It looks like the other blogs have links in their headers too.

**Comment by cthomasONRR** [comment]
@lpgoldstein Cool thanks for the explanation- I also found this link that I think should be imbedded in text:
image

**Review by cthomasONRR — APPROVED** [review]
Looks great! Approved :)

**Comment by Maroyafaied** [comment]
@lpgoldstein so it looks like Kaitlyn's blog overridden this one. I should've merged this one before asking you to create a PR for Kaitlyn's. I'll look into fixing.

**Pull request merged**
