### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-blog-nrrd.app.cloud.gov/)

- Sarah's blog post 
- update footer with privacy policy

### CODE REVIEW

**Review by mcharg — APPROVED** [review]

**Comment by jennmalcolm** [comment]
@Maroyafaied do you want me to update the date for Sarah's blog post to tomorrow?

**Comment by Maroyafaied** [comment]
@jennmalcolm yes please. Thanks

**Comment by jennmalcolm** [comment]
Also, @mcharg and @Maroyafaied, are you ok with me making  the mention of VSFS a link to https://vsfs.state.gov/?

**Comment by mcharg** [comment]
@jennmalcolm I'm fine with that.

**Comment by Maroyafaied** [comment]
@jennmalcolm ya that's fine.

**Comment by jennmalcolm** [comment]
The preview looks good, but this PR is going from master to dev, so that needs to be reversed @Maroyafaied. Otherwise, I approve.

**Pull request closed without merging**
