### PR TITLE
Stepping out of my comfort zone – into management   

### PR DESCRIPTION
**Pull request by Maroyafaied**
[Preview](https://dev-blog-nrrd.app.cloud.gov/transition-to-management/)

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@cthomasONRR thanks, I pushed an update.

**Comment by cthomasONRR** [comment]
@Maroyafaied You should update your position title in the signature area: 
image

**Comment by Maroyafaied** [comment]
@cthomasONRR made both changes.

**Review by cthomasONRR — APPROVED** [review]
Looks great! Approving now :)

**Comment by cvojslavek** [comment]
This was an enjoyable read, thanks @Maroyafaied. I have a few minor suggested changes, below:

1. Remove extra space after analyst:
image

2. At the end of the 4th paragraph under Building trust and transitioning to management, remove passive voice to: "I believe that as the team started achieving the goals we set together, it helped me gain the trust of my team."
image

**Comment by mcharg** [comment]
@Maroyafaied I pulled in dev to get Jerome's changes in and fix the preview link, which was overwritten with Jerome's branch.

**Comment by Maroyafaied** [comment]
@mcharg thank you, you're always on top of it and so helpful!

**Comment by mcharg** [comment]
@Maroyafaied I also put in @cvojslavek's edits.

**Review by cvojslavek — APPROVED** [review]

**Review by mcharg — APPROVED** [review]

**Review by daniel-coleman-1 — APPROVED** [review]
Looks good!

**Pull request merged**
