### PR TITLE
Tree Test Blog Post 

### PR DESCRIPTION
**Pull request by lpgoldstein**
https://dev-blog-nrrd.app.cloud.gov/treetest/

### CODE REVIEW

**Comment by Maroyafaied** [comment]
image

**Comment by lpgoldstein** [comment]
@Maroyafaied Sure! We still need to go through and proof read now that we have everything rendering correctly.

**Comment by jennmalcolm** [comment]
@lpgoldstein should I wait to review it until you make your changes or would you like my review now?

**Comment by mcharg** [comment]
@Maroyafaied What looks like periods is just how it renders the space after the tail in the Y.

**Comment by mcharg** [comment]
@jennmalcolm You can go ahead and review now.

**Comment by jennmalcolm** [comment]
Could you divide this sentence in two? I think its a bit long/complicated. 
image

**Comment by jennmalcolm** [comment]
Extra word 
image

**Comment by jennmalcolm** [comment]
Should be ever 
image

**Comment by jennmalcolm** [comment]
Aside from the typos I noted, I'm only concerned about the width of the in-page tables. Those are much wider than the rest of the page. I might be able to help with this if you want me to try.

**Comment by mcharg** [comment]
@jennmalcolm That would be helpful.  I have no idea how to change the width of the tables.

**Comment by mcharg** [comment]
@jennmalcolm The html table is showing up as text on my machine. 
image

**Comment by jennmalcolm** [comment]
Yeah @mcharg we don't have any table styles set up for the blog. I'm deleting the html table and just putting your markdown one back in. If you want to fix the width, we better ask one of the developers for help setting up table styles. It's probably not that big of deal, so I'll just approve once my html removal commit goes through.

**Review by jennmalcolm — APPROVED** [review]

**Review by mcharg — APPROVED** [review]

**Pull request merged**
