### PR TITLE
cat-blog.md

### LINKED ISSUE #118: Put Cat's blog post in markdown and create a PR

### PR DESCRIPTION
**Pull request by cvojslavek**
Fixes #118
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/)

### CODE REVIEW

**Comment by mcharg** [comment]
@cvojslavek Is there a reason this link is italic? 
image

**Comment by mcharg** [comment]
For the ONRResource link, we should add a note that the link won't work if you're not on the vpn. 
image

**Review by lpgoldstein — APPROVED** [review]

**Review by cthomasONRR — APPROVED** [review]
Everything looks good to me. Thanks for writing such a thoughtful blog post!!

**Comment by cvojslavek** [comment]
@mcharg It's italicized because it is the title of the post. Maybe it is not as formal as a blog post.

Good call. What about: ONRResource has cross training and job rotation opportunities (connect to VPN to access).

**Comment by mcharg** [comment]
@cvojslavek I think that works.

**Review by mcharg — APPROVED** [review]

**Review by daniel-coleman-1 — APPROVED** [review]
Looks great!

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@jlouis-onrr @mojobnichols can one of you figure out why this branch has conflict and I can't merge it? Thanks

**Comment by jlouis-onrr** [comment]
@Maroyafaied, the conflict is now resolved.

**Pull request merged**
