### PR TITLE
508-study-blog-post

### LINKED ISSUE #123: Put 508 blog post in markdown

### PR DESCRIPTION
**Pull request by cthomasONRR**
Fixes #123
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/508-Study/)

### CODE REVIEW

**Comment by cthomasONRR** [comment]
This blog post is ready for review. I can't get my profile picture to show up... could someone help me with that? Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR I'll look into it.

**Comment by Maroyafaied** [comment]
@cthomasONRR it shows up for me now, can you check if that fixed it?

**Comment by cthomasONRR** [comment]
@Maroyafaied It shows up for me now. Thanks!

**Review by Maroyafaied — APPROVED** [review]

**Comment by daniel-coleman-1** [comment]
One issue:
Screenshot 2021-12-29 113946

The period should be inside the quote instead of following it.  Aside from that, looks good!

**Review by daniel-coleman-1 — APPROVED** [review]

**Review by mcharg — APPROVED** [review]
Looks good.  I cropped Christine's image to a square to make it less blurry.

**Review by lpgoldstein — APPROVED** [review]

**Comment by cthomasONRR** [comment]
@Maroyafaied is the blog ready to go live or are we waiting for a larger merge?

**Comment by Maroyafaied** [comment]
@cthomasONRR I will merge it with the new monthly data.

**Pull request merged**
