### PR TITLE
Create Christa's blog post "Implementing agile tools"

### LINKED ISSUE #128: Put Christa's blog post in markdown and create PR
https://teams.microsoft.com/l/file/5776C9C0-2E9E-4C70-8E18-A1E241BB765F?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FBlog%2FChrista's%20blog.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

### PR DESCRIPTION
**Pull request by daniel-coleman-1**
Fixes #128 
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/implementing-agile-tools/)

### CODE REVIEW

**Comment by daniel-coleman-1** [comment]
@jlouis-onrr I'm not able to get this preview link to work, any idea what's going on?

**Comment by jlouis-onrr** [comment]
@daniel-coleman-1, looks like previews get pushed into dev automatically based on this commit from @mojobnichols, https://github.com/ONRR/blog-nrrd/commit/2f0afd7855290eac2fdeb144550fcc7bf258a739#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47

Are you not seeing these updates in dev?  https://dev-blog-nrrd.app.cloud.gov/

**Comment by mcharg** [comment]
@daniel-coleman-1 You should be appending the folder name the post is in, not the branch name.  I pulled down the branch and didn't see a new post folder.  Where is this post located?

**Comment by mcharg** [comment]
@daniel-coleman-1 Just found it.  Here's the preview link.
https://dev-blog-nrrd.app.cloud.gov/implementing-agile-tools/

**Comment by mcharg** [comment]
@daniel-coleman-1 I haven't read through the whole thing, but right off the bat, it's linking to Cat's blog post, not Christa's.

**Comment by daniel-coleman-1** [comment]
@mcharg and @jlouis-onrr I apologize for not responding earlier, I took a long lunch and hung late for a bit.

**Comment by daniel-coleman-1** [comment]
@CM805 @Maroyafaied thoughts:
- Can we promote/link to Service Now and their task board?
- I added the Github link to our NRRD issues, is that too transparent/close to home for us?
- What do you think about the call to action in the final paragraph?

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 @CM805 here are my answers and additional comments

**- Can we promote/link to Service Now and their task board?**
_I don't believe the intention of the blog is to "promote" Servicenow, the blog is about implementing agile tools so it's ok to talk about a tool similar to ZenHub.  After it's mentioned, can you put in parenthesis "this isn't an endorsement of Servicenow"_

**- I added the Github link to our NRRD issues, is that too transparent/close to home for us?**
_We work in the open and GitHub is a public repository, anyone can already see it and our work. We've linked to GitHub many times in our blogs, the whole point is to be open and transparent. Please also link to ZenHub._

**- What do you think about the call to action in the final paragraph?**
_It's fine but we need to specify this is for ONRR employees only, and also the link in the paragraph above it (participate in a job rotation) goes to Onrresource so we need to mention you need to be connected to VPN. You can refer to Cat's blog in her last paragraph as an example._ 

**Other Comments** 
-  In the first paragraph, you can just link to the blog when Christa mentions it, no need to say it can be found here then the link.
- We use the abbreviation ONRR  and RRM without writing out what it stands for, not all our blog readers are ONRR employees.
- please add @cthomasONRR and @mcharg to review the blog after the changes have been implemented. Thanks

**Comment by CM805** [comment]
I originally wrote this as an article for the RRM newsletter, so thanks for looking at it from the outside perspective.  Since this is going to a larger audience, outside of ONRR, it might be good to mention some other platforms that can be used to create a Kanban board, such as Microsoft Planner (which ONRR employees also have access to), Trello, and Asana.  But I do agree that we should mentioned that we are not endorsing those.

**Comment by daniel-coleman-1** [comment]
- Linked to zenhub
- added disclaimer about endorsing products
- spelled out ONRR and RRM
- specified rotation is for ONRR employees and included copy about connecting to VPN
- added copy about Microsoft Planner, Trello, and Asana

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 can you include the checklist that was put together for reviewing blogs for reviewers. Thanks

**Review by cthomasONRR — APPROVED** [review]
I just read the blog. Looks good! All links work and didn't find any grammar issues.

**Comment by daniel-coleman-1** [comment]
Checklist:

- [ ]  Check for typos, spelling, and grammar. Track changes in the shared doc and allow the author to accept your suggested changes.
- [ ]   Put the post into Hemingway to check reading level. If it's above grade 10, make a note and suggest simplifications.
- [ ]   Are paragraphs too long, or sentences overly complex? If so, offer simplifications to reduce the text's cognitive load.
- [ ]   Offer suggestions to swap out common modifiers (great, very, really, etc.).
- [ ]   Confirm the post follows the NRRD Content Style Guide.
- [ ]   Confirm that images all make sense in context and add value to the text.
- [ ]   Confirm the source file is available for any images to prevent a loss in resolution.
- [ ]   Confirm header levels are used correctly.
- [ ]   Check if there are other blog posts would add value to readers of this post and offer links to those posts.
 - [ ]  Are products referenced that ONRR should not endorse? If so, offer removal and explain your reasoning to the author.
- [ ]   Check that all content that should be attributed to a person or group is, and offer attribution if needed.
- [ ]   Finally, comment on the GitHub issue to let the author know you made edits and notes in the shared document.

**Comment by daniel-coleman-1** [comment]
I'm getting Grade 10 in Hemingway, but also getting Grade 11 with the same text.

**Review by Maroyafaied — APPROVED** [review]
I got grade 10 on hemmingway. I checked of the things I looked out for on the list.

**Comment by mcharg** [comment]
@Maroyafaied Do we want to keep in the links to the cross training email address and ONRResource page given that this is for an external audience?

**Comment by mcharg** [comment]
@daniel-coleman-1 On the links to the previous blog post and wiki, we usually just link words in the sentence rather that putting in the full title of the post of wiki page.  Should we do that for consistency?

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 @mcharg It's ok to link to onrresource and cross training email since we did it in Cat's blog , as long as we're specifying this is for ONRR employees only. I agree with being consistent and linking to the words rather than putting the whole title.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied @mcharg I left the call to action with links in and edited the link text to Christa's first blog post.

I'd like to send the cross training email a message when we publish asking if they get an increase in traffic following the post - we can also feature all of the cross training blog posts in a WYMHM or some other kind of internal outreach from leadership.

The last thing I have to edit is the publish date, I currently have it set as though we are publishing tomorrow.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Thanks. We have been mentioning the cross training blogs in WYMHM and will continue to do that, I also send them to person that handles cross training. You can leave the date for now, and I will change it once I do the next release.

**Comment by mcharg** [comment]
@daniel-coleman-1 This is what I would link.
image

Also, I don't think we usually capitalize wiki.
image

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I think it's better to insert the link here. 
image

**Comment by Maroyafaied** [comment]
Just saw that @mcharg suggested the same thing about the blog link and I agree with her about the wiki link.

**Review by mcharg — APPROVED** [review]

**Pull request merged**
